on: push

env:
  CARGO_TERM_COLOR: always
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⬇️ checkout repository
        uses: actions/checkout@v3
      - name: 🛠 setup cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: ♻️ cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.os }}
      - name: ✅ run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  lint:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ checkout repository
        uses: actions/checkout@v3
      - name: 🛠 setup cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: ♻️ cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ubuntu-latest
      - name: 🔍 run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy